export const API_ROOT = (process.env.NODE_ENV === 'development') ? 'http://124.193.195.42:7096' : 'http://prd.domain'
export const API_LOGIN = API_ROOT + '/flowserver/service/login'
export const API_UPDATE_PASSWORD = API_ROOT + '/flowserver/service/updatePassword'
export const API_QUERY_APPROVAL_LIST = API_ROOT + '/flowserverer/service/queryApprovalList'
export const API_SHOW_BILL = API_ROOT + '/flowserver/service/showBill'
export const API_SHOW_BILL_DET = API_ROOT + '/flowserver/service/showBillDet'
export const API_QUERY_CHANGE_USER_LIST = API_ROOT + '/flowserver/service/queryChangeUserList'
export const API_COMMIT_APPROVAL = API_ROOT + '/flowserver/service/commitApproval'
